apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-dev
  namespace: argocd
spec:
  project: tools
  sources:
    - repoURL: oci://registry-1.docker.io/bitnamicharts/
      chart: mongodb
      targetRevision: 0.9.0
      helm:
        releaseName: mongodb-dev
        valueFiles:
          - $values/apps/mongodb/helm-values/dev/values.yaml
    - repoURL: https://github.com/open-liontechsolution/fintech-personal-tools.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
