---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-password
  namespace: mongodb-dev
spec:
  encryptedData:
    password: AgATTdZYjE37FuiWlPTK6kXagLmbqVjFpKXrcEfqXaOWPbb2W2ddmNkiAwV5xptHVJh0KuVFlRChJAircBid/zQLAv/CL5Rqr9B9Jf6G82Nz3iNPKrDXvw32/jFea4ewCvFgWrolaDgRlS8WusNBwPgy2YO1iEvxd073jWrhFXTshxQrE7KnIG9/7wc6z8gwMZKcLPm3YLP5XlC+W7wIKO69czrBu39+XL0bvA2iAr0zWNYNTpKjiMYESzAxkBRnWtw77EBhhexxoE7GADsQDPxQGW/D6azMC9BEbbnqYXoRkDYrnDMDTHSr+hE9c271rfBKofInx4+1sfiq00J8pOJR41qg6XiO/no15N4o/yun5B5nnQuUZ05o/bJse5WRRVW8elQywr2qt9d2kFvQNWa7BBiWgOqYma1l0susmCuGBWobu5UZ7X793mDR/b/QzMWwYSZo9VHwGqArqadJDk721FkcgyfrO6CXpdqgxvvi91vVMGTLe6oxuOsPJ2ePhpCZAMtcmgkAMCbnC87QBqlH6QMfW8+A6Is664ZnU6YxjEQm3lPVZAX5F/PTYMfa9mCs9u5tmrKEzG3D9JWlHwFU/6vlJka2vo6kJxEMMFJSnwvrFiSZIywknmesJBtt7ZXu3PcdzPt5Nhcqs7A7yDRykrVM+hLtvX3JJSOa2os3ufgHukCAbZjs3G/46AHEO4iRFiWCT4xv9U2PtDdiZwVM4K0=
  template:
    metadata:
      creationTimestamp: null
      name: admin-password
      namespace: mongodb-dev
    type: Opaque
