---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-password
  namespace: mongodb
spec:
  encryptedData:
    password: AgB0stnUZiE9s3PJpqFr/6/x2TKdXG3cnrx0G3JUXJrJPO+AcnbjGKCJvUFVK3HbDv5KUpsb0jK/9Wsp4aFx4dZl0p4eewAFA/1geOGqDkZWHlz3YFKYmgbXZzlW8vVfdYriYrGvWOyjQwvZAsmy6F09r6YB9KPBQYKfsa5IDFio34RK6hSghbhGIIE9x8Lp3vopxtlIL947GHeLNQPCJoT5s8VNfS9X7WpcppLsqzVrmGyTiiT4/sTVqWojat+gDVlmiWnnQh05pk232rw7zXlP+i5v1R8qAiuCytmfwt6CNAltfonsaD0+I7JrFbz2MacY5hbEwlajW0qrYws8Y/3iybGiWfzxfcZx9NLdP3GEotzZqCpsZlTpmfPO2NQnf+UdV99I03qrI+9aUmWXM1grJNFeAYBPvK8udA0RukT3llSMXdEWLpOaDg9z+DwvLS+csnvVvm1kA1qZKKjha86mTJXeubXcwjxadK32rJcuGcaReOJ76e+N4F5Ui1pkDlZLwNPUklHpkK2z3dxR51NQaWpIm/c8eut3XgItz+HG35pttD++WRgIMqH7700E1EmNxqhoNdEvWuKugcH8xvaJYJmCCfnE5/vESc3e2ZSzhmeNeUtglsptaWCnsiAIUebOPrYhwPn1QV/atpDxirLAGBsEndhEO4CvjX+x2OCXXf/ky4KdhcOFvqhoLuZz4r/Sh26dC8iWYlWBAyLyx6n7j1s=
  template:
    metadata:
      creationTimestamp: null
      name: admin-password
      namespace: mongodb
    type: Opaque
