# Valores para MongoDB Community Edition - Entorno de QA

# Imagen y configuración básica
image:
  repository: mongodb/mongodb-community-server
  tag: 6.0.8  # Utilizar la versión estable más reciente de MongoDB 6.0
  pullPolicy: IfNotPresent

# Arquitectura: replicaset para entorno de QA para mayor disponibilidad
architecture: replicaset

# Autenticación
auth:
  enabled: true
  rootUser: root
  rootPassword: ""  # Se generará automáticamente si se deja vacío
  existingSecret: ""
  
# Configuración de recursos
resources:
  limits:
    cpu: 1500m
    memory: 2Gi
  requests:
    cpu: 750m
    memory: 1Gi

# Configuración de persistencia
persistence:
  enabled: true
  storageClass: "longhorn"  # Usando Longhorn como proveedor de almacenamiento
  accessModes:
    - ReadWriteOnce
  size: 16Gi
  
# Configuración del servicio
service:
  type: ClusterIP
  port: 27017
  annotations: {}

# Configuración del StatefulSet
statefulset:
  updateStrategy: RollingUpdate
  podManagementPolicy: OrderedReady
  
# Configuración de Pods
podAnnotations:
  io.cilium/proxy-visibility: '<Mongodb/TCP/27017>'
  
podSecurityContext:
  enabled: true
  fsGroup: 1001
  
containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true
  
# Configuración del readiness probe  
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
  
# Configuración del liveness probe
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

# Configuración de replicación
replicaCount: 3
  
# Configuración de TLS (desactivada por defecto)
tls:
  enabled: false
  
# Configuración de métricas
metrics:
  enabled: true
  serviceMonitor:
    enabled: true  # Activado para QA para monitoreo
