# Valores para MongoDB Community Operator - Entorno de QA

# Configuración básica del operador
operator:
  # El operador monitorea esta configuración de MongoDB
  watchNamespace: mongodb-qa

# Configuración del ResourceBundle que contendrá el operador
resourceBundle:
  enabled: true

mongodb:
  # Nombre de la instancia MongoDB
  name: mongodb
  
  # Configuración de la réplica - 3 réplicas para alta disponibilidad
  replicaCount: 3
  
  # Configuración de usuarios
  users:
    - name: admin-user
      db: admin
      passwordSecretRef:
        name: mongodb-admin-password
      roles:
        - name: root
          db: admin
  
  # Configuración de seguridad
  security:
    tls:
      enabled: false
      
  # Configuración del almacenamiento persistente
  storage:
    dataVolume:
      persistentVolumeClaim:
        storageClassName: longhorn
        resources:
          requests:
            storage: 16Gi
  
  # Configuración de recursos
  resources:
    limits:
      cpu: 1500m
      memory: 2Gi
    requests:
      cpu: 750m
      memory: 1Gi
  
  # Configuración del StatefulSet personalizada
  statefulSet:
    spec:
      template:
        spec:
          containers:
          - name: mongod
            resources:
              limits:
                cpu: 1500m
                memory: 2Gi
              requests:
                cpu: 750m
                memory: 1Gi
          # Anotaciones para integración con Cilium
          annotations:
            io.cilium/proxy-visibility: '<Mongodb/TCP/27017>'
          # Configuración de afinidad para distribuir pods en nodos diferentes
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - mongodb
                  topologyKey: kubernetes.io/hostname
          tolerations: []

# Configuración de métricas para Prometheus
metrics:
  enabled: true
  prometheus:
    serviceMonitor:
      enabled: true
