apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-qa
  namespace: argocd
spec:
  project: tools
  sources:
    - repoURL: https://mongodb.github.io/helm-charts
      targetRevision: 1.7.0
      chart: mongodb-community-server
      helm:
        releaseName: mongodb-qa
      
    - repoURL: https://github.com/open-liontechsolution/fintech-personal-tools.git
      targetRevision: HEAD
      path: apps/mongodb/helm-values/qa
      
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb-qa
  syncPolicy:
    automated:
      # Desactivamos el prune automático para evitar que ArgoCD elimine recursos que no controla
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
