apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-kubernetes-operator
  namespace: argocd
spec:
  project: tools
  sources:
    - repoURL: https://mongodb.github.io/helm-charts
      chart: community-operator
      targetRevision: 0.9.0
      helm:
        releaseName: mongodb-kubernetes-operator
        valueFiles:
          - $values/apps/mongodb/helm-values/operator/values.yaml
    - repoURL: https://github.com/open-liontechsolution/fintech-personal-tools.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
