apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-kubernetes-operator
  namespace: argocd
spec:
  project: tools
  sources:
    repoURL: https://github.com/open-liontechsolution/fintech-personal-tools.git
    targetRevision: HEAD
    path: apps/mongodb/helm-values/operator
    helm:
      releaseName: mongodb-kubernetes-operator
      valueFiles:
        - values.yaml
      chart: community-operator
      repoURL: https://mongodb.github.io/helm-charts
      targetRevision: 0.9.0
      
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb
  syncPolicy:
    automated:
      # Desactivamos el prune automático para evitar que ArgoCD elimine recursos que no controla
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true