environment: qa
namespace: fintech-personal-qa
replicas: 2

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

storage:
  size: 3Gi

ingress:
  host: verdaccio-qa.fintech.local
  webServer: "internal"
  tls:
    enabled: false
    issuer: ""
