apiVersion: v1
kind: Secret
metadata:
  name: frpc-secrets
  namespace: fintech-personal-dev
type: Opaque
data:
  # Estos valores deben ser reemplazados con versiones codificadas en base64
  # Ejemplo: echo -n "my-token" | base64
  server_addr: VlBTX0lQX09SX0RPTUFJTg==  # Valor real: VPS_IP_OR_DOMAIN
  token: U0VDVVJFVElaSUVUT<TRUS!>===  # Valor real: SECURE_TOKEN
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frpc-web-app-config
  namespace: fintech-personal-dev
data:
  frpc.ini: |
    [common]
    # Valores sensibles cargados desde secretos de Kubernetes
    server_addr = ${SERVER_ADDR}
    server_port = 7000
    token = ${FRP_TOKEN}
    tls_enable = true
    log_level = info
    login_fail_exit = false
    reconnect_interval = 5
    
    [web-app]
    type = http
    local_ip = 127.0.0.1
    local_port = 3000
    custom_domains = web-app.yourdomain.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: fintech-personal-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      # Contenedor principal de la aplicación
      - name: web-app
        image: web-app:latest
        ports:
        - containerPort: 3000
      
      # Sidecar de FRP con variables de entorno desde secretos
      - name: frpc-sidecar
        image: snowdreamtech/frpc:0.51.3
        command: 
        - /bin/sh
        - -c
        - |
          # Reemplazar variables en la configuración con valores de secretos
          export SERVER_ADDR=$(cat /etc/frp/secrets/server_addr)
          export FRP_TOKEN=$(cat /etc/frp/secrets/token)
          envsubst < /etc/frp/templates/frpc.ini > /etc/frp/frpc.ini
          # Iniciar frpc con la configuración generada
          /usr/bin/frpc -c /etc/frp/frpc.ini
        volumeMounts:
        - name: frpc-config-template
          mountPath: /etc/frp/templates
        - name: frpc-secrets
          mountPath: /etc/frp/secrets
          readOnly: true
      
      volumes:
      - name: frpc-config-template
        configMap:
          name: frpc-web-app-config
      - name: frpc-secrets
        secret:
          secretName: frpc-secrets
