apiVersion: v1
kind: ConfigMap
metadata:
  name: verdaccio-config
  namespace: fintech-personal
  labels:
    app: verdaccio
data:
  config.yaml: |
    storage: /verdaccio/storage
    auth:
      htpasswd:
        file: /verdaccio/config/htpasswd
    uplinks:
      npmjs:
        url: https://registry.npmjs.org/
    packages:
      '@fintech-personal/*':
        access: $authenticated
        publish: $authenticated
        proxy: npmjs
      '**':
        access: $all
        publish: $authenticated
        proxy: npmjs
    logs:
      - {type: stdout, format: pretty, level: http}
    http:
      max_body_size: 100mb
