apiVersion: apps/v1
kind: Deployment
metadata:
  name: verdaccio
  namespace: fintech-personal
  labels:
    app: verdaccio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verdaccio
  template:
    metadata:
      labels:
        app: verdaccio
    spec:
      containers:
      - name: verdaccio
        image: verdaccio/verdaccio:6
        ports:
        - containerPort: 4873
        env:
        - name: VERDACCIO_PORT
          value: "4873"
        - name: VERDACCIO_HOST
          value: "verdaccio.fintech-personal.svc.cluster.local"
        volumeMounts:
        - name: verdaccio-storage
          mountPath: /verdaccio/storage
        - name: verdaccio-config
          mountPath: /verdaccio/config
      volumes:
      - name: verdaccio-storage
        persistentVolumeClaim:
          claimName: verdaccio-storage
      - name: verdaccio-config
        configMap:
          name: verdaccio-config
          items:
          - key: config.yaml
            path: config.yaml
