apiVersion: v1
kind: Service
metadata:
  name: verdaccio
  namespace: fintech-personal
  labels:
    app: verdaccio
spec:
  selector:
    app: verdaccio
  ports:
  - name: http
    port: 4873
    targetPort: 4873
  type: ClusterIP
