bindPort = {{ .Envs.FRPS_BIND_PORT }}

# Configure the web server to enable the dashboard for frps.
# dashboard is available only if webServer.port is set.
webServer.addr = "{{ .Envs.FRPS_DASHBOARD_ADDR }}"
webServer.port = {{ .Envs.FRPS_DASHBOARD_PORT }}
webServer.user = "{{ .Envs.FRPS_DASHBOARD_USER }}"
webServer.password = "{{ .Envs.FRPS_DASHBOARD_PASSWORD }}"

# Authentication token
auth.token = "{{ .Envs.FRP_TOKEN }}"
