# FRP Server Configuration (frps)
# Using correct environment variable names as defined in docker-compose.yaml

bindPort = {{ .Envs.FRPS_BIND_PORT }}

# Configure the web server to enable the dashboard for frps
# Using 0.0.0.0 to listen on all interfaces instead of a specific IP
webServer.addr = "0.0.0.0"
webServer.port = {{ .Envs.FRPS_WEBSERVER_PORT }}
webServer.user = "{{ .Envs.FRPS_WEBSERVER_USER }}"
webServer.password = "{{ .Envs.FRPS_WEBSERVER_PASSWORD }}"

# Authentication token
auth.token = "{{ .Envs.FRPS_AUTH_TOKEN }}"
