# FRP Server Configuration (frps)
# Using direct values instead of templates for troubleshooting

bindPort = 7000

# Configure the web server to enable the dashboard for frps
webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin"

# Authentication token
auth.token = "test-token"
