# FRP Server Configuration (frps)
# Using correct environment variable names as defined in docker-compose.yaml

bindPort = {{ .Envs.FRPS_BIND_PORT }}

# Configure the web server to enable the dashboard for frps
webServer.addr = "{{ .Envs.FRPS_WEBSERVER_ADDR }}"
webServer.port = {{ .Envs.FRPS_WEBSERVER_PORT }}
webServer.user = "{{ .Envs.FRPS_WEBSERVER_USER }}"
webServer.password = "{{ .Envs.FRPS_WEBSERVER_PASSWORD }}"

# Authentication token
auth.token = "{{ .Envs.FRPS_AUTH_TOKEN }}"
