apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: verdaccio
  namespace: {{.Values.namespace}}
  labels:
    app: verdaccio
    environment: {{.Values.environment}}
  annotations:
    kubernetes.io/ingress.class: "cilium"
    io.cilium/ingress-controller: "true"
    io.cilium/web-server: "{{.Values.ingress.webServer}}"
    {{- if .Values.ingress.tls.enabled }}
    io.cilium/tls: "true"
    cert-manager.io/cluster-issuer: "{{.Values.ingress.tls.issuer}}"
    {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{.Values.ingress.host}}
    secretName: verdaccio-tls-{{.Values.environment}}
  {{- end }}
  rules:
  - host: {{.Values.ingress.host}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: verdaccio
            port:
              number: 4873
