apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verdaccio-storage-{{.Values.environment}}
  namespace: {{.Values.namespace}}
  labels:
    app: verdaccio
    environment: {{.Values.environment}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.storage.size}}
  storageClassName: longhorn
