apiVersion: v1
kind: Service
metadata:
  name: verdaccio
  namespace: {{.Values.namespace}}
  labels:
    app: verdaccio
    environment: {{.Values.environment}}
spec:
  selector:
    app: verdaccio
    environment: {{.Values.environment}}
  ports:
  - name: http
    port: 4873
    targetPort: 4873
  type: ClusterIP
