# Valores para el despliegue de FRP en entorno de QA

# Configuración global
global:
  namespace: fintech-personal-qa
  environment: qa

# Configuración del servidor (frps)
frps:
  enabled: true
  replicaCount: 1
  image:
    repository: snowdreamtech/frps
    tag: 0.51.3
    # Aseguramos compatibilidad con ARM64 para Raspberry Pi
    pullPolicy: IfNotPresent
  
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 150m
      memory: 192Mi
  
  service:
    type: ClusterIP
    ports:
      - name: frps
        port: 7000
        targetPort: 7000
      - name: dashboard
        port: 7500
        targetPort: 7500
  
  # Configuración para ingress con Cilium
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: cilium
    hosts:
      - host: frps-qa.local
        paths:
          - path: /
            pathType: Prefix
            port: 7500
  
  # Configuración para persistencia
  persistence:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 2Gi
    mountPath: /data
  
  # Configuración del archivo frps.ini
  config:
    content: |
      [common]
      bind_port = 7000
      dashboard_port = 7500
      dashboard_user = admin
      dashboard_pwd = qa_admin_password_change_me
      token = qa_secure_token_change_me
      tls_enable = true
      log_file = /data/frps.log
      log_level = info
      log_max_days = 7
      max_pool_count = 100
      max_ports_per_client = 15
      enable_prometheus = true

# Configuración del cliente (frpc)
frpc:
  enabled: true
  replicaCount: 1
  image:
    repository: snowdreamtech/frpc
    tag: 0.51.3
    # Aseguramos compatibilidad con ARM64 para Raspberry Pi
    pullPolicy: IfNotPresent
  
  resources:
    limits:
      cpu: 150m
      memory: 192Mi
    requests:
      cpu: 75m
      memory: 96Mi
  
  # Configuración para persistencia
  persistence:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 2Gi
    mountPath: /data
  
  # Configuración del archivo frpc.ini
  config:
    content: |
      [common]
      server_addr = frps
      server_port = 7000
      token = qa_secure_token_change_me
      tls_enable = true
      log_file = /data/frpc.log
      log_level = info
      log_max_days = 7
      login_fail_exit = false
      reconnect_interval = 5
      
      # Ejemplo para exponer web-app
      [web-app]
      type = http
      local_ip = web-app
      local_port = 3000
      custom_domains = web-app-qa.local
      
      # Ejemplo para exponer MongoDB
      [mongodb]
      type = tcp
      local_ip = mongodb
      local_port = 27017
      remote_port = 27017
