# Valores para MongoDB Community Operator - Entorno de Desarrollo

# Configuración básica del operador
operator:
  # El operador monitorea esta configuración de MongoDB
  watchNamespace: mongodb-dev

# Configuración del ResourceBundle que contendrá el operador
resourceBundle:
  enabled: true

mongodb:
  # Nombre de la instancia MongoDB
  name: mongodb
  
  # Configuración de la réplica
  replicaCount: 1
  
  # Configuración de usuarios
  users:
    - name: admin-user
      db: admin
      passwordSecretRef:
        name: mongodb-admin-password
      roles:
        - name: root
          db: admin
  
  # Configuración de seguridad
  security:
    tls:
      enabled: false
      
  # Configuración del almacenamiento persistente
  storage:
    dataVolume:
      persistentVolumeClaim:
        storageClassName: longhorn
        resources:
          requests:
            storage: 8Gi
  
  # Configuración de recursos
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  
  # Configuración del StatefulSet personalizada
  statefulSet:
    spec:
      template:
        spec:
          containers:
          - name: mongod
            resources:
              limits:
                cpu: 1000m
                memory: 1Gi
              requests:
                cpu: 500m
                memory: 512Mi
          affinity: {}
          tolerations: []
          # Anotaciones para integración con Cilium
          annotations:
            io.cilium/proxy-visibility: '<Mongodb/TCP/27017>'

# Configuración de métricas para Prometheus
metrics:
  enabled: true
  prometheus:
    serviceMonitor:
      enabled: true
