# Valores para MongoDB Community Edition - Entorno de Producción

# Imagen y configuración básica
image:
  repository: mongodb/mongodb-community-server
  tag: 6.0.8  # Utilizar la versión estable más reciente de MongoDB 6.0
  pullPolicy: IfNotPresent

# Arquitectura: replicaset para alta disponibilidad en producción
architecture: replicaset

# Autenticación
auth:
  enabled: true
  rootUser: root
  rootPassword: ""  # Se generará automáticamente si se deja vacío
  existingSecret: ""
  
# Configuración de recursos
resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

# Configuración de persistencia
persistence:
  enabled: true
  storageClass: "longhorn"  # Usando Longhorn como proveedor de almacenamiento
  accessModes:
    - ReadWriteOnce
  size: 32Gi
  
# Configuración del servicio
service:
  type: ClusterIP
  port: 27017
  annotations: {}

# Configuración del StatefulSet
statefulset:
  updateStrategy: RollingUpdate
  podManagementPolicy: OrderedReady
  
# Configuración de Pods
podAnnotations:
  io.cilium/proxy-visibility: '<Mongodb/TCP/27017>'
  
podSecurityContext:
  enabled: true
  fsGroup: 1001
  
containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true
  
# Configuración del readiness probe  
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
  
# Configuración del liveness probe
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

# Configuración de replicación
replicaCount: 3
  
# Configuración de TLS
tls:
  enabled: true
  autoGenerated: true  # Generar certificados automáticamente
  
# Configuración de métricas
metrics:
  enabled: true
  serviceMonitor:
    enabled: true  # Activado para producción para monitoreo

# Configuración de copia de seguridad
backup:
  enabled: true
  cronjob:
    schedule: "0 2 * * *"  # Ejecutar a las 2 AM todos los días
    successfulJobsHistoryLimit: 3
    failedJobsHistoryLimit: 3
