# Valores para MongoDB Community Edition - Entorno de Producción

# Versión Community oficial de MongoDB
image:
  registry: docker.io
  repository: mongodb/mongodb-community-server 
  tag: 6.0.8
  pullPolicy: IfNotPresent

# Arquitectura: replicaset para alta disponibilidad
architecture: replicaset
replicaCount: 3

# Autenticación
auth:
  enabled: true
  rootUser: root
  rootPassword: ""  # Se generará automáticamente
  usernames: []
  passwords: []
  databases: []

# Configuración de recursos
resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

# Configuración de persistencia
persistence:
  enabled: true
  storageClass: "longhorn"
  size: 32Gi
  accessModes:
    - ReadWriteOnce

# Configuración de servicio
service:
  type: ClusterIP
  port: 27017
  nodePort: ""
  clusterIP: ""
  annotations: {}

# Configuración de seguridad
podSecurityContext:
  enabled: true
  fsGroup: 1001

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true
  privileged: false

# Configuración de despliegue
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

# Configuración de afinidad
affinity: {}
nodeSelector: {}
tolerations: []

# Configuración de métricas
metrics:
  enabled: true
  serviceMonitor:
    enabled: true

# Configuración de TLS
tls:
  enabled: true
  autoGenerated: true  # Generar certificados automáticamente
  
# Configuración específica de MongoDB
arbiter:
  enabled: false

hidden:
  enabled: false
  
extraFlags: []
extraEnvVars: []

# Configuración para integrarse con Cilium
podAnnotations:
  io.cilium/proxy-visibility: '<Mongodb/TCP/27017>'

# Configuración de copias de seguridad
backup:
  enabled: true
  cronjob:
    schedule: "0 2 * * *"
    image:
      registry: docker.io
      repository: bitnami/mongodb
      tag: latest
    persistence:
      enabled: true
      storageClass: "longhorn"
      size: 8Gi
