apiVersion: batch/v1
kind: Job
metadata:
  generateName: mongodb-db-manager-
  namespace: mongodb-dev
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
      - name: mongodb-db-manager
        image: mongo:4.4.18
        command:
        - /bin/bash
        - -c
        - |
          echo "Iniciando el procesamiento de usuarios para MongoDB..."
          
          # Esperar a que MongoDB esté disponible
          echo "Esperando a que MongoDB esté disponible..."
          until mongo --host mongodb-0.mongodb --eval "db.adminCommand('ping')" --quiet; do
            echo "MongoDB no está disponible aún. Esperando 5 segundos..."
            sleep 5
          done
          
          # Inicializar array de bases de datos
          DATABASES="[]"
          
          # Debug: Mostrar contenido del directorio de secretos
          echo "Contenido del directorio /secrets:"
          ls -la /secrets/
          
          # En volúmenes proyectados, los secretos se montan directamente
          if [ -f "/secrets/database" ] && [ -f "/secrets/username" ] && [ -f "/secrets/password" ]; then
            DB_NAME=$(cat "/secrets/database")
            DB_USER=$(cat "/secrets/username")
            DB_PASS=$(cat "/secrets/password")
            
            echo "Encontrada información para la base de datos: $DB_NAME"
            
            # Crear el JSON para el script de MongoDB
            DATABASES="[{\"name\":\"$DB_NAME\",\"username\":\"$DB_USER\",\"password\":\"$DB_PASS\"}]"
          else
            echo "No se encontraron los archivos esperados en /secrets/"
            echo "Archivos presentes:"
            find /secrets -type f | sort
          fi
          
          # Exportar la lista de bases de datos como variable de entorno
          export MONGODB_DATABASES="$DATABASES"
          echo "Bases de datos a procesar: $MONGODB_DATABASES"
          
          # Verificar si MongoDB está configurado con autenticación
          echo "Verificando configuración de seguridad de MongoDB..."
          AUTH_ENABLED=$(mongo --host mongodb-0.mongodb --eval "try { db.serverCmdLineOpts().parsed.security.authorization || 'disabled' } catch(e) { 'unknown' }" --quiet)
          
          echo "Estado de la autenticación en MongoDB: $AUTH_ENABLED"
          
          # Verificar si el usuario admin ya existe
          echo "Verificando si existe el usuario admin..."
          ADMIN_EXISTS=$(mongo --host mongodb-0.mongodb --eval "try { db = db.getSiblingDB('admin'); db.system.users.find({user:'admin'}).count() > 0 } catch(e) { false }" --quiet)
          
          echo "¿Existe el usuario admin?: $ADMIN_EXISTS"
          
          # Definir comando de MongoDB basado en la configuración
          if [ "$AUTH_ENABLED" == "enabled" ]; then
            echo "MongoDB tiene autenticación habilitada, intentando autenticar..."
            
            # Intentar autenticar con diferentes variantes
            mongo --host mongodb-0.mongodb -u "$MONGO_INITDB_ROOT_USERNAME" -p "$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase admin --eval "printjson(db.adminCommand('ping'))" --quiet
            
            if [ $? -eq 0 ]; then
              echo "✅ Autenticación exitosa con credenciales de secret"
              MONGO_AUTH_CMD="mongo --host mongodb-0.mongodb -u \"$MONGO_INITDB_ROOT_USERNAME\" -p \"$MONGO_INITDB_ROOT_PASSWORD\" --authenticationDatabase admin"
            else
              echo "❌ Autenticación fallida. No se puede continuar cuando la autenticación está habilitada pero las credenciales no funcionan."
              echo "Por favor verifica que las credenciales en el secret mongodb-secret son correctas."
              exit 1
            fi
          else
            echo "⚠️ MongoDB está ejecutándose sin autenticación habilitada, continuando sin credenciales."
            echo "Es altamente recomendable habilitar la autenticación en entornos de producción."
            
            # Si MongoDB no tiene autenticación, creamos el usuario admin si no existe
            if [ "$ADMIN_EXISTS" == "false" ]; then
              echo "Creando usuario admin ya que no existe..."
              mongo --host mongodb-0.mongodb admin --eval "db.createUser({user: '$MONGO_INITDB_ROOT_USERNAME', pwd: '$MONGO_INITDB_ROOT_PASSWORD', roles: ['root']})"
              
              if [ $? -eq 0 ]; then
                echo "✅ Usuario admin creado exitosamente"
              else
                echo "❌ No se pudo crear el usuario admin"
              fi
            fi
            
            # Usar MongoDB sin autenticación
            MONGO_AUTH_CMD="mongo --host mongodb-0.mongodb"
          fi
          
          # Ejecutar el script de gestión de usuarios
          if [ "$MONGODB_DATABASES" != "[]" ]; then
            echo "Ejecutando script de gestión de usuarios..."
            eval "$MONGO_AUTH_CMD /scripts/user-management.js"
            
            if [ $? -eq 0 ]; then
              echo "✅ Procesamiento de usuarios completado con éxito."
            else
              echo "❌ El script de gestión de usuarios falló con código $?"
              exit 1
            fi
          else
            echo "No hay bases de datos para procesar"
          fi
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: root-password
        volumeMounts:
        - name: scripts-volume
          mountPath: /scripts
        - name: mongodb-managed-secrets
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: scripts-volume
        configMap:
          name: mongodb-db-manager
          defaultMode: 0755
      - name: mongodb-managed-secrets
        projected:
          sources:
          - secret:
              name: mongodb-credentials
          # Añadir aquí más secrets con la anotación mongodb.io/managed=true si es necesario
      restartPolicy: OnFailure
