apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
  namespace: mongodb-dev
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: mongo-init
        image: mongo:4.4.18
        command:
        - /bin/bash
        - -c
        - |
          # Esperar a que todos los nodos de MongoDB estén listos
          echo "Esperando a que todos los nodos MongoDB estén disponibles..."
          sleep 30
          
          # Inicializar el replica set
          echo "Inicializando el replica set..."
          mongo --host mongodb-0.mongodb --port 27017 -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin /configmap/init-replica.js
          
          echo "Replica set inicializado correctamente"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: root-password
        volumeMounts:
        - name: init-configmap
          mountPath: /configmap
      volumes:
      - name: init-configmap
        configMap:
          name: mongodb-init
          defaultMode: 0777
      restartPolicy: OnFailure
