apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb-dev
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  selector:
    app: mongodb
  clusterIP: None  # Headless service para StatefulSet
