apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-user-manager-scripts
  namespace: mongodb-dev
data:
  init-user.js: |
    // Este script crea o actualiza usuario en MongoDB
    // Recibe variables de entorno: DB_NAME, DB_USER, DB_PASS
    
    const dbName = process.env.DB_NAME;
    const dbUser = process.env.DB_USER;
    const dbPass = process.env.DB_PASS;
    
    if (!dbName || !dbUser || !dbPass) {
      print("ERROR: Faltan variables de entorno requeridas (DB_NAME, DB_USER, DB_PASS)");
      quit(1);
    }
    
    // Conectar a la base de datos
    const db = db.getSiblingDB(dbName);
    
    // Verificar si el usuario ya existe
    const userExists = db.getUser(dbUser);
    
    if (userExists) {
      print(`El usuario ${dbUser} ya existe en ${dbName}, actualizando contraseña...`);
      db.changeUserPassword(dbUser, dbPass);
      print("Contraseña actualizada");
    } else {
      print(`Creando nuevo usuario ${dbUser} en ${dbName}...`);
      db.createUser({
        user: dbUser,
        pwd: dbPass,
        roles: [{ role: "readWrite", db: dbName }]
      });
      print("Usuario creado exitosamente");
    }
    
    print(`Configuración completada para ${dbName}`);
  
  setup.sh: |
    #!/bin/sh
    set -e
    
    echo "Esperando a que MongoDB esté listo..."
    sleep 15
    
    echo "Extrayendo información del Secret..."
    if [ -f /secrets/database ] && [ -f /secrets/username ] && [ -f /secrets/password ]; then
      export DB_NAME=$(cat /secrets/database)
      export DB_USER=$(cat /secrets/username)
      export DB_PASS=$(cat /secrets/password)
      
      echo "Creando usuario $DB_USER para la base de datos $DB_NAME..."
      
      # Ejecutar script de JavaScript para MongoDB
      mongo --host mongodb-0.mongodb:27017 \
        -u $MONGO_INITDB_ROOT_USERNAME \
        -p $MONGO_INITDB_ROOT_PASSWORD \
        --authenticationDatabase admin \
        /scripts/init-user.js
      
      echo "Proceso completado correctamente"
    else
      echo "No se encontró información completa en el Secret"
      exit 1
    fi
