apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-db-manager
  namespace: mongodb-dev
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: mongodb-manager-sa
      initContainers:
      - name: setup-users
        image: mongo:4.4.18
        command:
        - /bin/bash
        - -c
        - |
          echo "Esperando a que MongoDB esté listo..."
          sleep 15
          
          echo "Extrayendo información del Secret..."
          # Verificar que el secret existe
          if [ -f /secrets/database ] && [ -f /secrets/username ] && [ -f /secrets/password ]; then
            DB_NAME=$(cat /secrets/database)
            DB_USER=$(cat /secrets/username)
            DB_PASS=$(cat /secrets/password)
            
            echo "Creando usuario $DB_USER para la base de datos $DB_NAME..."
            
            # Crear usuario en MongoDB
            mongo --host mongodb-0.mongodb:27017 -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin <<EOF
            use $DB_NAME;
            
            if (db.getUser("$DB_USER")) {
              print("El usuario $DB_USER ya existe, actualizando contraseña...");
              db.changeUserPassword("$DB_USER", "$DB_PASS");
            } else {
              print("Creando nuevo usuario $DB_USER...");
              db.createUser({
                user: "$DB_USER",
                pwd: "$DB_PASS",
                roles: [{ role: "readWrite", db: "$DB_NAME" }]
              });
            }
            
            print("Configuración completada para $DB_NAME");
            EOF
            
            echo "Proceso completado correctamente"
          else
            echo "No se encontró información completa en el Secret"
          fi
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: root-password
        volumeMounts:
        - name: mongodb-secret-volume
          mountPath: /secrets
      containers:
      - name: completion
        image: busybox
        command: ["echo", "Proceso de configuración de MongoDB completado"]
      volumes:
      - name: mongodb-secret-volume
        secret:
          secretName: mongodb-credentials
      restartPolicy: OnFailure
