apiVersion: batch/v1
kind: Job
metadata:
  generateName: mongodb-init-
  namespace: mongodb-dev
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: mongo-init
        image: mongo:4.4.18
        command:
        - /bin/bash
        - -c
        - |
          # Esperar a que todos los nodos de MongoDB estén disponibles
          echo "Esperando a que todos los nodos de MongoDB estén disponibles..."
          
          # Esperar a que mongodb-0 esté disponible
          echo "Esperando a que mongodb-0.mongodb esté disponible..."
          until mongo --host mongodb-0.mongodb --eval "printjson(db.serverStatus())" --quiet; do
            echo "mongodb-0.mongodb no está listo todavía, esperando 5 segundos..."
            sleep 5
          done
          echo "mongodb-0.mongodb está listo."
          
          # Esperar a que mongodb-1 esté disponible
          echo "Esperando a que mongodb-1.mongodb esté disponible..."
          until mongo --host mongodb-1.mongodb --eval "printjson(db.serverStatus())" --quiet; do
            echo "mongodb-1.mongodb no está listo todavía, esperando 5 segundos..."
            sleep 5
          done
          echo "mongodb-1.mongodb está listo."
          
          # Esperar a que mongodb-2 esté disponible
          echo "Esperando a que mongodb-2.mongodb esté disponible..."
          until mongo --host mongodb-2.mongodb --eval "printjson(db.serverStatus())" --quiet; do
            echo "mongodb-2.mongodb no está listo todavía, esperando 5 segundos..."
            sleep 5
          done
          echo "mongodb-2.mongodb está listo."
          
          echo "Todos los nodos están disponibles. Iniciando configuración del replica set..."
          
          # Intentar inicializar el replica set
          echo "Configurando el replica set en mongodb-0.mongodb..."
          mongo --host mongodb-0.mongodb --port 27017 /configmap/init-replica.js
          
          # Esperar a que el replica set esté establecido
          echo "Verificando que el replica set se ha establecido..."
          sleep 10
          
          # Verificar el estado del replica set
          echo "Estado del replica set:"
          mongo --host mongodb-0.mongodb --eval "printjson(rs.status())" --quiet
          
          echo "Inicialización completada."
        volumeMounts:
        - name: init-configmap
          mountPath: /configmap
      volumes:
      - name: init-configmap
        configMap:
          name: mongodb-init
          defaultMode: 0777
      restartPolicy: OnFailure
