apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-user-manager
  namespace: mongodb-dev
spec:
  schedule: "*/15 * * * *"  # Ejecutar cada 15 minutos
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: mongodb-manager-sa
          containers:
          - name: user-manager
            image: mongo:4.4.18
            command:
            - /bin/bash
            - -c
            - |
              echo "Iniciando la sincronización de usuarios MongoDB..."
              sleep 10  # Esperar a que MongoDB esté estable
              
              # Obtener los secrets gestionados por MongoDB
              MANAGED_SECRETS=$(kubectl get secrets -n mongodb-dev -o jsonpath='{range .items[?(@.metadata.annotations.mongodb\.io/managed=="true")]}{.metadata.name}{"\n"}{end}')
              
              if [ -z "$MANAGED_SECRETS" ]; then
                echo "No hay secrets gestionados por MongoDB para procesar"
                exit 0
              fi
              
              for SECRET_NAME in $MANAGED_SECRETS; do
                echo "Procesando secret: $SECRET_NAME"
                
                # Extraer y decodificar datos del secret
                DB_NAME=$(kubectl get secret $SECRET_NAME -n mongodb-dev -o jsonpath='{.data.database}' | base64 --decode)
                DB_USER=$(kubectl get secret $SECRET_NAME -n mongodb-dev -o jsonpath='{.data.username}' | base64 --decode)
                DB_PASS=$(kubectl get secret $SECRET_NAME -n mongodb-dev -o jsonpath='{.data.password}' | base64 --decode)
                
                if [ -z "$DB_NAME" ] || [ -z "$DB_USER" ] || [ -z "$DB_PASS" ]; then
                  echo "Datos incompletos en el secret $SECRET_NAME, se omite"
                  continue
                fi
                
                echo "Configurando base de datos $DB_NAME con usuario $DB_USER..."
                
                # Crear script temporal para la gestión de usuarios
                cat > /tmp/create_user.js << EOL
                use ${DB_NAME};
                
                if (db.getUser("${DB_USER}")) {
                  print("El usuario ${DB_USER} ya existe, actualizando contraseña...");
                  db.changeUserPassword("${DB_USER}", "${DB_PASS}");
                } else {
                  print("Creando nuevo usuario ${DB_USER}...");
                  db.createUser({
                    user: "${DB_USER}",
                    pwd: "${DB_PASS}",
                    roles: [{ role: "readWrite", db: "${DB_NAME}" }]
                  });
                }
                
                print("Configuración completada para ${DB_NAME}");
                EOL
                
                # Ejecutar el script de MongoDB
                mongo --host mongodb-0.mongodb:27017 -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin /tmp/create_user.js
                
                echo "Procesamiento completado para $SECRET_NAME"
              done
              
              echo "Sincronización de usuarios MongoDB completada"
            env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: root-password
          restartPolicy: OnFailure
