apiVersion: batch/v1
kind: Job
metadata:
  generateName: mongodb-init-
  namespace: mongodb-dev
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: mongo-init
        image: mongo:4.4.18
        command:
        - /bin/bash
        - -c
        - |
          # Esperar a que MongoDB esté disponible
          echo "Esperando a que MongoDB esté disponible..."
          sleep 30
          
          # Intentar inicializar el replica set
          echo "Intentando inicializar el replica set..."
          mongo --host mongodb-0.mongodb --port 27017 /configmap/init-replica.js
          
          # Salir con éxito (el script de init-replica.js maneja los errores)
          exit 0
        volumeMounts:
        - name: init-configmap
          mountPath: /configmap
      volumes:
      - name: init-configmap
        configMap:
          name: mongodb-init
          defaultMode: 0777
      restartPolicy: OnFailure
