---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: mongodb-dev
spec:
  encryptedData:
    root-password: AgBSCD/A1jGzjtg3YygBgPX226g1uNZL54OdZ6E3Vqzd3Mp5H8o85EzuKCmbb3pSoq1n6TBIEIQ8J+FPFB5qaPf9ov5PDmALjb7FwlNzhbaOl6iys+/Flkm4jPApiGQSJ2DA+yB+A7zzes/l51UN3KMBgCDQNXO+GdkZ63rNu1RP423ZoO6ZTL3Sc9p0oo5m3xKdTjG43iJj9UczWjHuHNDY/o3GWwYlOssFcQKzUmzR+VHVcyjoYCO8IHzZHBmuVVMfM6d9VQXX7ig0Evio62cF9IpTSUH+AUXIFnnMOPgoYps1rYiAuuAzhjN+fcqVhUR4L9P3eBInnb5VBcBqflsDlJJv9t2uZhOQj1DtEH+ngOVYI2DSICMPUcDt4tI90XxvlRbZmcYR0z9GzVyMBS9RVbR/cqzVt1bcu80mAEik/5Qwe0sAfdLUIN0wXH+V6BKWJ6eNZ+ipKQBFuzQp18/ZWgGCFvkx1hcQIZq2bK/FeGl9d34lJDs7Epk4rHCzEfmPRd0HXxYzMGNS5RfST0DPMb47pbvgNgBRnB+Ld0T81z8YC0owpmUfqClpqkD3jdLtycoeC/CmbLg82G8WbRkBzi+VSy7Pef1h9dUQPyLJRTGBeim5w5s0WxTm60lubTnlwVyiAAwes/gzXk/WCE3umN5HYBh5w4jGN7vwBy7gCBQGhmK2KiqhRjJ80EGCdApQfh0YPR+ADsdOPHjQI9rR9dc=
    root-username: AgAwILDgCVT2KhnPSMP4A/X0T1GvpbLreqN1GrPmeVRPA8y0OwfkHIclC44rd+kgFJEKjWYJYHrNjf/edjfCHoqMtca8nOCPgpPoEjgFz/j0E70dcNUuC5JclnwY/Hgw4vwbRuipB+bClU5tt1s78eABh9DnTLEOS6u7U4urajqr6PunpyZyBuMeLFn3nsYArYUusG8k+tNHHAXgtnzrB/S77e+PGEwzQ/kXZHk4/TENpSO7YSMAi8khJZ6kLuZ6TjBXqopP3pW/QJqcgdvYjPaVlC3J5KI1UjzxZ0rTdE9GN6L7bw3iNop/z4cez0IYU4hwimKlmyzAxMn1tlZAuhUzgzGB4UUsgFNfFdMTeRcadcZbNegtX6gNUg5QcCH1MUs+M1Me5CksKKR92xVygh8UdR/culABAYA04xE7uX7ej2bk6OJYjXPgfjxqYIEBIP3+n4GOSM8ut0PNRokD4aiZbvxqU7JDH/5LYrdiEHqQrJVsxHTVsXqWmHiN+skn0h3u/ObTvp6MZYdnAajr64O77pIdK4jzQYg7DpaE6ULI6SQeFLwcwPf2piHc3RUSCVepikIXr6k+tkwq269jPiCJLYUVjSjeXFS8UizKSxyBLBXrvs/XNKaxteatyAnDudZw5nWttPzFuMKNwI1fzqPPe/yebbAZ8QVq6/WjY2/LdMNIs9oyhf0h009rIuM2ENjorXuXuA==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: mongodb-dev
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-keyfile
  namespace: mongodb-dev
spec:
  encryptedData:
    mongodb-keyfile: AgCMSTPNDIN3wq4+QjriyjXRuQrGTBEkWNr620hbMxbECEl+PmKOjlrJbOndT/ygl0PFYxvM+acDS0JNRmrso98MnRL95bNS3bB2QDu3ifk0DIz3y3jLUQ2tKMYLhgNI2Ju4Z/o2yjOihmA9vwBd8hvjMxpnceE8EPS3iLAP9YwPNw55mH4DLBiszhVPmAVq4CGmg8KrvZgBFzsztqXRMN+2bazFcrj+589IRKgIQxkbGy3eWWyy8tkx2stu6hMA9Cy12cOVOze9CNepnDVCRu0V3Smmi2FsSzUKGGrfImJ+xAOVVmoHgNULcFIe7fMEGjeruN25kaeBv2KGgUSLY1VnlBocPIUOTwym9BO8c6kzUM1uFRuyW2Wxi5eAHe/nhSUiKxK00213VSmku98in30utE2hyzmQA0S3Y2p5s0WnsncOI16lbCmNKJ4d0Ff+Z9vnWsxEhFyRJlhmP2ulzhpO0tT3GiG5gNVHaj5vzjSO4p46+sHx0YXuDv38JrbDL1V9cF+8IeCb3cCEJWMDFpKNXYqqmXSvNDDQHcKkjh/YJJj04lT3RD8ulLsDK4kONGUeg6xJQn89w9mSN5NuKcNzKhEkX+fhZXLkmvyPiMGOzjNX0kL8KB8SX9g5HE1EbYck6GQULgmAwuMiaxq38ORp84t7EbdfiflPcmmfQkOa21F7xCBegFy+pKkl97wG25Omr1/CzpY4R7IudcP8Qb3wwWhXO3VipztzXd5RIJy7nx7i7Ov530M+Flr3kzM2X3WAOZ0F0CDFjYmF574xLVz+z+6dOli0kh+TW/p2qWf4pDFNCXcDv9tLPhGftyyOqqJCgb6A4z7B6LGmgNEByhcFpvS5Ks1+MKp2Ldfyb1kjm4nV/4xxzT9y7zaZYRnBsUxOWIw0PNMXTzsFCeVkRxTpcjuxkM8/Y7sWKjBHx0OBmPU8TMH5nN1SS8utPj9+DM07lNaaOsMNvuBmtSb8cMEo+fT+BOW8liu/0OcGU1y1YcWynjp3K4lGjYvS++AWaMLuqnHLinDFPef+VfbQqlaKf1lBauFGeFJ2LqrTFbC20LdSZbzq8g5AnUel6XkwqWMKWyvxAjonXAz1/V8fwA11Q8NXKOaga+SKE57sgF+Swf3Uqvv8DAFF1dqpumDuMpXt1GJ3GtVx0pZD7EW32WmpEPkbTWWwp9UFZv2rOzuoeuGF0fhOWru2iv8fE6wVlIvCvg78sZ3ZPY4YOBlqmhsk/0QUThhmGEm21mskAj1YWZCEbo3RmFZd78UoJqkeBQ2Xg6EdH3oOCnKIgYk9jZxZ8DbW4ke8jHAhAvXQSr/6zcUuohJGIDs99riJjHS5/f27mN/Fcp+eU8l9lSUpPFjC4vtzXnnaJ5HfvYSyCEEZ6oELXGuaIhIM
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-keyfile
      namespace: mongodb-dev
    type: Opaque
