---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: mongodb-dev
spec:
  encryptedData:
    root-password: AgA2QUKVJ/tQTQt2i/huWJpfJ8TisL9Zk5U7PvUdQ3b0Qax5QepVI6HWplAd5nzTglGRtoVf89zYVm9crjl7NdgZrssspLcIm/G/qnRWCnjNDcCwxGgNjmnqTHYvUK5XYN1a5sflcQbFZPY/fgI8IJw9I01YIsDjQwDjSl6JZduQ4R99AHI/sf+4ExGSK2nplQ4Nm6UrXgQYMUOyPu9Ut35AJosAtnceWiQVDeBBAgM9tDJ2V5he7wskQuAdZTQSo3xzRuUoL3ucHqik3sL6wRdDoIqCjrLR/4pMFRcuft08p8S4CEiTDffO8yi763Bxlh4U3o54Y/6WxKdI7IKn9byEKP5XUJoxZ3SELwRrqiIqXzYemxO/aeJlMPt+aPf9Fij4Wkn6oTpXg0u7wLXYuX7Yc30kHG3qEt4czJ2aP9pWUIh7pC6lp3FJZH0+BxdNS2jYmOQp/wvjwMxUwVGzlNe4x5ld7XgdTC938WMlsjvA9msfQKMrA++3SvEGI1dWuQyRpthFbJzYyd6o3MshLtAi7XKQA4yRdD/FyS/DCFTQO8ZisBdAoKwy5Z/2nLt0qsKlPlrIP0ZCgX9uHNbhm0EGeZGxhNJsOKiGu+xsi9TPLmWAiXVNcHU4grrQMSPRkuJimV584b2rj+t7WGi5d36yNY9JAtRy/oCSJyCZsJDhOVX2g2LH02PWHF+7VlEiJuscoqqIcPO0OsnWY9o4vhShwqQ=
    root-username: AgCRII9zrHm/NbesI2hZq+7NywWgpfAR1FsS1i6Q2d2kOWGCmvg0qdS7lmT9kqqNUXVgr4rD8mh7k7ZDr7UikbIxgSrGkw1p54PeYedDto7hW/TzCYkTeLq0ulitvoTIQkR4X2gfwaGz870j7h+9gfIZM/X6gMaLqVjhuXmXqlQia1hLi1fnkO50k5zw+etJ1RxpnC+4z6ShITFiqvIalTDxkT4+gHtU4Mcosi/N4IiSK1Ic6tdqP/YeMAOoArC3x9+fav9PqtH+y/O7Z61/BWaEefhf8Z/gX45jUFef9hqqZes8pu6NXTlhbNnh0HfKhIMP0RWsv9BveiQj3brlC/+oXrzH9s3JvIRKtGa1rFVfXodd7k3BqY9KNOZwjKcEP6dfxgb1p6som4QZqjvim2WojhJcuQkepM1DCjK1fLq4EWP/iDaIEqN68zO8xyYK6eKCggB7ohEeOhvVRhdQYyFbZvLjW0YWJBOQK3K1xtZQu3gt13/tLfnv6s6i64w1emAPte3AEszd/2yLHCa36AtZFIuUU98seMfZkh42wkIIegdc+vMJP+iIdc5f3Yx6C6jhlHGjqbLtfLAIsKdcR8lFSbgQZ71sS7HVRq+8/LEQJ/wMiMg/vJ2X5sxcYBdHI1LCx1uPVkOk37LIvG7F2X/McySesinTgxN9JhBqQQm5TXX6k+kHJbZ8Pbo+6dGfXyAzkKLk6Q==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: mongodb-dev
    type: Opaque
