## Verdaccio Helm Chart valores para entorno DEV

# Asignamos namespace específico del entorno
fullnameOverride: "verdaccio"
nameOverride: "verdaccio"

# Número de réplicas para el entorno de desarrollo
replicaCount: 1

# Configuración de imagen
image:
  repository: verdaccio/verdaccio
  tag: "6"
  pullPolicy: IfNotPresent

# Recursos asignados al pod
resources:
  limits:
    cpu: 2
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Configuración del servicio
service:
  type: LoadBalancer
  port: 4873
  loadBalancerIP: 192.169.2.34

# Configuración de ingress usando Cilium
ingress:
  enabled: false
  ingressClassName: "cilium"
  annotations:
    io.cilium/ingress-controller: "true"
    io.cilium/web-server: "internal"
  hosts:
    - host: verdaccio-dev.fintech.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Configuración de almacenamiento usando Longhorn
persistence:
  enabled: true
  storageClass: "longhorn"
  size: 8Gi
  accessMode: ReadWriteOnce

# Configuración personalizada de Verdaccio
configMap:
  storage: /verdaccio/storage/data
  auth:
    htpasswd:
      file: /verdaccio/storage/htpasswd
      max_users: 1000
  uplinks:
    npmjs:
      url: https://registry.npmjs.org/
      maxage: 30m
      max_fails: 5
      fail_timeout: 5m
      timeout: 60s
      cache: true
  packages:
    '@fintech-personal/*':
      access: $all
      publish: $all
      unpublish: $all
      proxy: npmjs
    '**':
      access: $all
      publish: $all
      unpublish: $all
      proxy: npmjs
  server:
    keepAliveTimeout: 60
  middlewares:
    audit:
      enabled: true
  logs:
    - {type: stdout, format: pretty, level: http}
  max_body_size: 100mb

secrets:
  # list of users and password for htpasswd plugin
  # This this is mounted as /verdaccio/auth/htpasswd on pods
  htpasswd:
    - username: "verdaccio"
      password: "verdaccio"

# Definir etiquetas para identificar el entorno
extraLabels:
  environment: dev

# existingSecret: "frpc-secrets"

extraManifests: 
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frpc
      namespace: verdaccio-dev
      labels:
        app: frpc
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: frpc
      template:
        metadata:
          labels:
            app: frpc
        spec:
          containers:
          - name: frpc
            image: snowdreamtech/frpc:0.62.1
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: config
              mountPath: /etc/frp/frpc.toml
              subPath: frpc.toml
            resources:
              limits:
                cpu: 150m
                memory: 192Mi
              requests:
                cpu: 75m
                memory: 96Mi
          volumes:
          - name: config
            secret:
              secretName: frpc-secrets
