apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: verdaccio-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
    # Ignorar recursos de Cilium
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/resource-exclusions: |
      - apiGroups: ["cilium.io"]
        kinds: ["CiliumIdentity"]
        clusters: ["*"]
spec:
  project: tools
  sources:
    - repoURL: https://charts.verdaccio.org
      targetRevision: 4.26.1
      chart: verdaccio
      helm:
        releaseName: verdaccio-dev
      
    - repoURL: https://github.com/open-liontechsolution/fintech-personal-tools.git
      targetRevision: HEAD
      path: apps/verdaccio/helm-values/dev
      
  destination:
    server: https://kubernetes.default.svc
    namespace: verdaccio-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
