apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: verdaccio-qa
  namespace: argocd
spec:
  project: tools
  sources:
    - repoURL: https://charts.verdaccio.org
      targetRevision: 4.26.1
      chart: verdaccio
      helm:
        releaseName: verdaccio-qa
      
    - repoURL: https://github.com/open-liontechsolution/fintech-personal-tools.git
      targetRevision: HEAD
      path: apps/verdaccio/helm-values/qa
      
  destination:
    server: https://kubernetes.default.svc
    namespace: verdaccio-qa
  syncPolicy:
    automated:
      # Desactivamos el prune automático para evitar que ArgoCD elimine recursos que no controla
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
