apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: verdaccio-qa
  namespace: argocd
spec:
  project: tools
  sources:
    - repoURL: https://charts.verdaccio.org
      targetRevision: 4.26.1
      chart: verdaccio
      helm:
        releaseName: verdaccio-qa
      
    - repoURL: https://github.com/open-liontechsolution/fintech-personal-tools.git
      targetRevision: HEAD
      path: apps/verdaccio/helm-values/qa
      
  destination:
    server: https://kubernetes.default.svc
    namespace: verdaccio-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  
  # Configuración para ignorar CiliumIdentity
  ignoreDifferences:
    - group: cilium.io
      kind: CiliumIdentity
      jqPathExpressions:
        - ".status"
        - ".metadata.resourceVersion"
        - ".metadata.finalizers"
        - ".metadata.managedFields"
