name: Deploy FRP Server

on:
  push:
    paths:
      - 'apps/frp/frps/docker/**'
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - production
          - qa
          - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    env:
      FRPS_BIND_PORT: ${{ vars.FRPS_BIND_PORT }}  # bind port for FRP Server
      FRPS_DASHBOARD_PORT: ${{ vars.FRPS_DASHBOARD_PORT }}  # Dashboard port
      FRPS_DASHBOARD_ADDR: ${{ vars.FRPS_DASHBOARD_ADDR }}  # Dashboard address
      FRPS_DASHBOARD_USER: ${{ secrets.FRPS_DASHBOARD_USER }}
      FRPS_DASHBOARD_PASSWORD: ${{ secrets.FRPS_DASHBOARD_PASSWORD }}
      FRP_TOKEN: ${{ secrets.FRP_TOKEN }}
      FRPC_VERDACCIO_PORT: ${{ vars.FRPC_VERDACCIO_PORT }}
      VPS_HOST: ${{ vars.VPS_HOST }}  # VPS host from environment variables
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create target directory on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT || 22 }}
          script: |
            sudo mkdir -p /opt/frps
            sudo chown $USER:$USER /opt/frps
      
      - name: Deploy configuration files to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT || 22 }}
          script: |
            # Debug - show what's in the directory before we start
            ls -la /opt/frps
      
      - name: Copy Docker Compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT || 22 }}
          source: "apps/frp/frps/docker/docker-compose.yaml"
          target: "/opt/frps/"
          strip_components: 4
      
      - name: Copy FRPS config file
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT || 22 }}
          source: "apps/frp/frps/docker/frps.toml"
          target: "/opt/frps/"
          strip_components: 4
      
      - name: Deploy and Start FRP Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT || 22 }}
          envs: FRPS_BIND_PORT,FRPS_DASHBOARD_PORT,FRPS_DASHBOARD_ADDR,FRPS_DASHBOARD_USER,FRPS_DASHBOARD_PASSWORD,FRP_TOKEN,FRPC_VERDACCIO_PORT
          script: |
            cd /opt/frps
            
            # Set environment variables directly in this session (original method)
            export FRPS_BIND_PORT=${{ env.FRPS_BIND_PORT }}
            export FRPS_DASHBOARD_PORT=${{ env.FRPS_DASHBOARD_PORT }}
            export FRPS_DASHBOARD_ADDR="${{ env.FRPS_DASHBOARD_ADDR }}"
            export FRPS_DASHBOARD_USER="${{ env.FRPS_DASHBOARD_USER }}"
            export FRPS_DASHBOARD_PASSWORD="${{ env.FRPS_DASHBOARD_PASSWORD }}"
            export FRP_TOKEN="${{ env.FRP_TOKEN }}"
            export FRPC_VERDACCIO_PORT="${{ env.FRPC_VERDACCIO_PORT }}"

            # Also create a .env file for docker-compose with environment variables
            cat > .env << EOF
            FRPS_BIND_PORT=${{ env.FRPS_BIND_PORT }}
            FRPS_DASHBOARD_PORT=${{ env.FRPS_DASHBOARD_PORT }}
            FRPS_DASHBOARD_ADDR=${{ env.FRPS_DASHBOARD_ADDR }}
            FRPS_DASHBOARD_USER=${{ env.FRPS_DASHBOARD_USER }}
            FRPS_DASHBOARD_PASSWORD=${{ env.FRPS_DASHBOARD_PASSWORD }}
            FRP_TOKEN=${{ env.FRP_TOKEN }}
            FRPC_VERDACCIO_PORT=${{ env.FRPC_VERDACCIO_PORT }}
            EOF
            
            # Secure the .env file
            chmod 600 .env
            
            # Show the variables (without showing sensitive values)
            echo "Using the following environment variables:"
            echo "FRPS_BIND_PORT=$FRPS_BIND_PORT"
            echo "FRPS_DASHBOARD_PORT=$FRPS_DASHBOARD_PORT"
            echo "FRPS_DASHBOARD_ADDR=$FRPS_DASHBOARD_ADDR"
            echo "FRPS_DASHBOARD_USER=$FRPS_DASHBOARD_USER"
            echo "(Password and token values hidden)"
            
            # Run Docker Compose with the environment variables from .env file
            docker compose -f docker-compose.yaml down
            docker compose -f docker-compose.yaml pull
            docker compose -f docker-compose.yaml up -d
            echo "FRP Server deployed successfully"
