name: Deploy FRP Server

on:
  push:
    paths:
      - 'apps/frp/frps/docker/**'
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - production
          - qa
          - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    env:
      FRPS_BIND_PORT: 7000  # Default bind port for FRP Server
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy configuration files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT || 22 }}
          source: "apps/frp/frps/docker/docker-compose.yaml,apps/frp/frps/docker/frps.toml"
          target: "/opt/frps"
      
      - name: Start FRP Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT || 22 }}
          envs: "FRPS_BIND_PORT=${{ env.FRPS_BIND_PORT }},FRPS_DASHBOARD_PORT=${{ secrets.FRPS_DASHBOARD_PORT }},FRPS_DASHBOARD_ADDR=${{ secrets.FRPS_DASHBOARD_ADDR }},FRPS_DASHBOARD_USER=${{ secrets.FRPS_DASHBOARD_USER }},FRPS_DASHBOARD_PASSWORD=${{ secrets.FRPS_DASHBOARD_PASSWORD }},FRP_TOKEN=${{ secrets.FRP_TOKEN }}"
          script: |
            cd /opt/frps
            
            docker-compose down
            docker-compose pull
            docker-compose up -d
            echo "FRP Server deployed successfully"
