name: Deploy FRP Server

on:
  push:
    paths:
      - 'apps/frp/frps/docker/**'
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - production
          - qa
          - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    env:
      FRPS_BIND_PORT: 7000  # Default bind port for FRP Server
      VPS_HOST: ${{ vars.VPS_HOST }}  # VPS host from environment variables
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create target directory on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT || 22 }}
          script: |
            sudo mkdir -p /opt/frps
            sudo chown $USER:$USER /opt/frps
      
      - name: Deploy configuration files to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT || 22 }}
          script: |
            # Debug - show what's in the directory before we start
            ls -la /opt/frps
      
      - name: Copy Docker Compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT || 22 }}
          source: "apps/frp/frps/docker/docker-compose.yaml"
          target: "/opt/frps/"
          strip_components: 4
      
      - name: Copy FRPS config file
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT || 22 }}
          source: "apps/frp/frps/docker/frps.toml"
          target: "/opt/frps/"
          strip_components: 4
      
      - name: Start FRP Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT || 22 }}
          envs: "FRPS_BIND_PORT=${{ env.FRPS_BIND_PORT }},FRPS_DASHBOARD_PORT=${{ secrets.FRPS_DASHBOARD_PORT }},FRPS_DASHBOARD_ADDR=${{ secrets.FRPS_DASHBOARD_ADDR }},FRPS_DASHBOARD_USER=${{ secrets.FRPS_DASHBOARD_USER }},FRPS_DASHBOARD_PASSWORD=${{ secrets.FRPS_DASHBOARD_PASSWORD }},FRP_TOKEN=${{ secrets.FRP_TOKEN }}"
          script: |
            cd /opt/frps
            
            # Create .env file for Docker Compose
            echo "FRPS_BIND_PORT=${FRPS_BIND_PORT}" > .env
            echo "FRPS_DASHBOARD_PORT=${FRPS_DASHBOARD_PORT}" >> .env
            echo "FRPS_DASHBOARD_ADDR=${FRPS_DASHBOARD_ADDR}" >> .env
            echo "FRPS_DASHBOARD_USER=${FRPS_DASHBOARD_USER}" >> .env
            echo "FRPS_DASHBOARD_PASSWORD=${FRPS_DASHBOARD_PASSWORD}" >> .env
            echo "FRP_TOKEN=${FRP_TOKEN}" >> .env
            
            # Show the .env file for debugging (without showing sensitive values)
            echo "Created .env file with the following variables:"
            grep -v 'PASSWORD\|TOKEN' .env
            echo "(Password and token values hidden)"
            
            # Run Docker Compose with the .env file
            docker compose -f docker-compose.yaml down
            docker compose -f docker-compose.yaml pull
            docker compose -f docker-compose.yaml up -d
            echo "FRP Server deployed successfully"
