apiVersion: apps/v1
kind: Deployment
metadata:
  name: frpc
  namespace: frpc-dev
  labels:
    app: frpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frpc
  template:
    metadata:
      labels:
        app: frpc
    spec:
      containers:
      - name: frpc
        image: snowdreamtech/frpc:0.51.3
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config
          mountPath: /etc/frp/frpc.toml
          subPath: frpc.toml
        - name: logs
          mountPath: /var/log
        resources:
          limits:
            cpu: 150m
            memory: 192Mi
          requests:
            cpu: 75m
            memory: 96Mi
      volumes:
      - name: config
        configMap:
          name: frpc-config
      - name: logs
        persistentVolumeClaim:
          claimName: frpc-logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frpc-logs
  namespace: frpc-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
